export const metadata = {
  title: "Welcome to extension",
  description: "Generated by create-nx-workspace",
};

export const dynamic = "error";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
